---
dns:
  nameserver:
  - 192.168.8.1
  - 192.168.9.1
  - dhcp://"eth1"
  - dhcp://"wwan0"
  - https://dns-google.com/dns-query
  - tls://dns.adguard.com
  - tls://dns-google.com/ 
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time-ios.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  default-nameserver:
  - 192.168.9.1
  - 192.168.8.1
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
secret: '123456'
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
ipv6: false
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
profile:
  store-selected: true
  store-fake-ip: true
proxy-groups:
- name: LB-AKRAB_6.1jtr
  type: load-balance
  strategy: round-robin
  disable-udp: false
  proxies:
  - AkrabV1
  - AkrabV2
  - AkrabV3
  - AkrabV4
  url: http://www.gstatic.com/generate_204
  interval: '300'
proxies:
- name: AkrabV1
  type: trojan
  server: idmsa.vpnexecutive.net
  port: 443
  password: 5a008244-da2f-4123-93ad-b739c91cb93c
  udp: true
  sni: chief-cdn.storage.googleapis.com
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-mode: gun
    grpc-service-name: trojan-grpc 
- name: AkrabV2
  type: trojan
  server: idmsa.vpnexecutive.net
  port: 443
  password: 5a008244-da2f-4123-93ad-b739c91cb93c
  udp: true
  sni: zoom.us
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-mode: gun
    grpc-service-name: trojan-grpc 
- name: AkrabV3
  type: trojan
  server: 104.17.3.81
  port: 443
  password: efd790e1-edb5-4d80-8582-92db4f6781e5
  udp: true
  sni: ctb.bukanvvip.my.id
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: "/bukanvvip"
    headers:
      Host: ctb.bukanvvip.my.id
- name: AkrabV4
  type: trojan
  server: ctb.bukanvvip.my.id
  port: 443
  password: efd790e1-edb5-4d80-8582-92db4f6781e5
  udp: true
  sni: chief-cdn.storage.googleapis.com
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: "/bukanvvip"
    headers:
      Host: ctb.bukanvvip.my.id
rules:
- DOMAIN-SUFFIX,m.me,DIRECT
- DOMAIN-SUFFIX,oculus.com,DIRECT
- DOMAIN-SUFFIX,oculuscdn.com,DIRECT
- DOMAIN-SUFFIX,rocksdb.org,DIRECT
- DOMAIN-SUFFIX,whatsapp.com,DIRECT
- DOMAIN-SUFFIX,whatsapp.net,DIRECT
- DST-PORT,3478,DIRECT
- DST-PORT,4244,DIRECT
- DST-PORT,5222,DIRECT
- DST-PORT,5223,DIRECT
- DST-PORT,5228,DIRECT
- DST-PORT,5288,DIRECT
- DST-PORT,5242,DIRECT
- DST-PORT,5349,DIRECT
- DST-PORT,34784,DIRECT
- DST-PORT,45395,DIRECT
- DST-PORT,50318,DIRECT
- DST-PORT,59234,DIRECT
- DOMAIN-KEYWORD,whatsapp-plus,DIRECT
- DOMAIN-SUFFIX,fna.whatsapp.net,DIRECT
- DOMAIN-SUFFIX,wa.me,DIRECT
- DOMAIN-SUFFIX,whatsapp.cc,DIRECT
- DOMAIN-SUFFIX,whatsapp.info,DIRECT
- DOMAIN-SUFFIX,whatsapp.org,DIRECT
- DOMAIN-SUFFIX,whatsapp.tv,DIRECT
- DOMAIN-SUFFIX,whatsappbrand.com,DIRECT
- IP-CIDR,31.13.64.0/24,DIRECT
- IP-CIDR,36.91.231.0/24,DIRECT
- IP-CIDR,50.22.240.0/24,DIRECT 
- IP-CIDR,50.23.90.0/24,DIRECT
- IP-CIDR,66.111.48.0/24,DIRECT
- IP-CIDR,66.111.49.0/24,DIRECT
- IP-CIDR,69.171.224.0/24,DIRECT
- IP-CIDR,102.132.96.0/24,DIRECT
- IP-CIDR,108.168.128.0/24,DIRECT
- IP-CIDR,157.240.0.0/24,DIRECT
- IP-CIDR,158.85.0.0/24,DIRECT
- IP-CIDR,169.44.0.0/24,DIRECT
- IP-CIDR,169.45.0.0/24,DIRECT
- IP-CIDR,169.47.0.0/24,DIRECT
- IP-CIDR,169.53.71.0/24,DIRECT
- IP-CIDR,169.53.81.0/24,DIRECT
- IP-CIDR,169.54.51.0/24,DIRECT
- IP-CIDR,169.54.55.0/24,DIRECT
- IP-CIDR,169.54.222.0/24,DIRECT
- IP-CIDR,169.55.64.0/24,DIRECT
- IP-CIDR,169.60.0.0/24,DIRECT
- IP-CIDR,169.61.101.0/24,DIRECT
- IP-CIDR,169.62.159.16/32,DIRECT
- IP-CIDR,169.63.64.0/24,DIRECT
- IP-CIDR,173.192.128.0/24,DIRECT
- IP-CIDR,173.193.224.0/24,DIRECT
- IP-CIDR,174.36.208.0/24,DIRECT
- IP-CIDR,174.37.243.0/24,DIRECT
- IP-CIDR,179.60.192.0/24,DIRECT
- IP-CIDR,184.173.128.0/24,DIRECT
- IP-CIDR,185.60.216.0/24,DIRECT
- IP-CIDR,192.155.212.0/24,DIRECT
- IP-CIDR,198.11.193.0/24,DIRECT
- IP-CIDR,198.11.251.0/24,DIRECT
- IP-CIDR,198.23.80.0/24,DIRECT
- IP-CIDR,208.43.115.0/24,DIRECT
- DST-PORT,3478,DIRECT
- DST-PORT,5222,DIRECT
- DOMAIN-KEYWORD,whatsapp,DIRECT
- DOMAIN,oculus.com,DIRECT
- DOMAIN,oculuscdn.com,DIRECT
- DOMAIN,rocksdb.org,DIRECT
- DOMAIN,whatsapp.com,DIRECT
- DOMAIN,whatsapp.net,DIRECT
- DOMAIN-SUFFIX,*.whatsapp.com,DIRECT
- DOMAIN-SUFFIX,*.whatsapp.net,DIRECT
- DOMAIN-SUFFIX,*.rocksdb.org,DIRECT
- DOMAIN-SUFFIX,*.oculuscdn.com,DIRECT
- DOMAIN-SUFFIX,*.oculus.com,DIRECT
- DOMAIN,web.whatsapp.com,DIRECT
- DOMAIN,www.whatsapp.com,DIRECT
- DOMAIN,api.whatsapp.com,DIRECT
- DOMAIN-SUFFIX,v.whatsapp.net,DIRECT
- DOMAIN,whatsapp.com,DIRECT
- DOMAIN,whatsapp.net,DIRECT
- DOMAIN,wa.me,DIRECT
- DOMAIN-SUFFIX,whatsapp.com,DIRECT
- DOMAIN-SUFFIX,whatsapp.net,DIRECT
- DOMAIN-SUFFIX,whatsapp.biz,DIRECT
- DOMAIN-SUFFIX,g.whatsapp.net,DIRECT
- DOMAIN-SUFFIX,snr.whatsapp.net,DIRECT
- DOMAIN-SUFFIX,v.whatsapp.net,DIRECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve

- DOMAIN-SUFFIX,vidio.com,AkrabV1
- DOMAIN-SUFFIX,vid.id,AkrabV1		
- DOMAIN,media-vidio-com.akamaized.net,AkrabV1
- DOMAIN,static-web-prod.static6.com,AkrabV1
- DOMAIN,static-web-prod-vidio.akamaized.net,AkrabV1
- DOMAIN,static-playback-vidio-com.akamaized.net,AkrabV1
- DOMAIN,etslive-2-vidio-com.akamaized.net,AkrabV1
- DOMAIN,token-media-vidio-com.akamaized.net,AkrabV1
- DOMAIN,geo-id-media-vidio-com.akamaized.net,AkrabV1
- DOMAIN,production-drm-vidio-com-event-1.akamaized.net,AkrabV1
- DOMAIN,geo-id-tl-media-vidio-com.akamaized.net,AkrabV1
- DOMAIN,license-global.pallycon.com,AkrabV1
- DOMAIN,sessions.bugsnag.com,AkrabV1
- DOMAIN-SUFFIX,pusher.com,AkrabV1
- DOMAIN,time.akamai.com,AkrabV1
  
- DOMAIN-SUFFIX,20thcenturystudios.com.au,AkrabV1
- DOMAIN-SUFFIX,20thcenturystudios.com.br,AkrabV1
- DOMAIN-SUFFIX,20thcenturystudios.jp,AkrabV1
- DOMAIN-SUFFIX,abc-studios.com,AkrabV1
- DOMAIN-SUFFIX,abc.com,AkrabV1
- DOMAIN-SUFFIX,abcnews.com,AkrabV1
- DOMAIN-SUFFIX,abcnews.edgesuite.net,AkrabV1
- DOMAIN-SUFFIX,adobedtm.com,AkrabV1
- DOMAIN-SUFFIX,adventuresbydisney.com,AkrabV1
- DOMAIN-SUFFIX,babble.com,AkrabV1
- DOMAIN-SUFFIX,babyzone.com,AkrabV1
- DOMAIN-SUFFIX,bam.nr-data.net,AkrabV1
- DOMAIN-SUFFIX,bamgrid.com,AkrabV1
- DOMAIN-SUFFIX,beautyandthebeastmusical.co.uk,AkrabV1
- DOMAIN-SUFFIX,braze.com,AkrabV1
- DOMAIN-SUFFIX,cdn.optimizely.com,AkrabV1
- DOMAIN-SUFFIX,conviva.com,AkrabV1
- DOMAIN-SUFFIX,d9.flashtalking.com,AkrabV1
- DOMAIN-SUFFIX,dilcdn.com,AkrabV1
- DOMAIN-SUFFIX,disney-asia.com,AkrabV1
- DOMAIN-SUFFIX,disney-discount.com,AkrabV1
- DOMAIN-SUFFIX,disney-plus.net,AkrabV1
- DOMAIN-SUFFIX,disney-portal.my.onetrust.com,AkrabV1
- DOMAIN-SUFFIX,disney-studio.com,AkrabV1
- DOMAIN-SUFFIX,disney-studio.net,AkrabV1
- DOMAIN-SUFFIX,disney.asia,AkrabV1
- DOMAIN-SUFFIX,disney.be,AkrabV1
- DOMAIN-SUFFIX,disney.bg,AkrabV1
- DOMAIN-SUFFIX,disney.ca,AkrabV1
- DOMAIN-SUFFIX,disney.ch,AkrabV1
- DOMAIN-SUFFIX,disney.co.il,AkrabV1
- DOMAIN-SUFFIX,disney.co.jp,AkrabV1
- DOMAIN-SUFFIX,disney.co.kr,AkrabV1
- DOMAIN-SUFFIX,disney.co.th,AkrabV1
- DOMAIN-SUFFIX,disney.co.uk,AkrabV1
- DOMAIN-SUFFIX,disney.co.za,AkrabV1
- DOMAIN-SUFFIX,disney.com,AkrabV1
- DOMAIN-SUFFIX,disney.com.au,AkrabV1
- DOMAIN-SUFFIX,disney.com.br,AkrabV1
- DOMAIN-SUFFIX,disney.com.hk,AkrabV1
- DOMAIN-SUFFIX,disney.com.tw,AkrabV1
- DOMAIN-SUFFIX,disney.cz,AkrabV1
- DOMAIN-SUFFIX,disney.de,AkrabV1
- DOMAIN-SUFFIX,disney.demdex.net,AkrabV1
- DOMAIN-SUFFIX,disney.dk,AkrabV1
- DOMAIN-SUFFIX,disney.es,AkrabV1
- DOMAIN-SUFFIX,disney.fi,AkrabV1
- DOMAIN-SUFFIX,disney.fr,AkrabV1
- DOMAIN-SUFFIX,disney.gr,AkrabV1
- DOMAIN-SUFFIX,disney.hu,AkrabV1
- DOMAIN-SUFFIX,disney.id,AkrabV1
- DOMAIN-SUFFIX,disney.in,AkrabV1
- DOMAIN-SUFFIX,disney.io,AkrabV1
- DOMAIN-SUFFIX,disney.it,AkrabV1
- DOMAIN-SUFFIX,disney.my,AkrabV1
- DOMAIN-SUFFIX,disney.my.sentry.io,AkrabV1
- DOMAIN-SUFFIX,disney.nl,AkrabV1
- DOMAIN-SUFFIX,disney.no,AkrabV1
- DOMAIN-SUFFIX,disney.ph,AkrabV1
- DOMAIN-SUFFIX,disney.pl,AkrabV1
- DOMAIN-SUFFIX,disney.pt,AkrabV1
- DOMAIN-SUFFIX,disney.ro,AkrabV1
- DOMAIN-SUFFIX,disney.ru,AkrabV1
- DOMAIN-SUFFIX,disney.se,AkrabV1
- DOMAIN-SUFFIX,disney.sg,AkrabV1
- DOMAIN-SUFFIX,disneyadsales.com,AkrabV1
- DOMAIN-SUFFIX,disneyarena.com,AkrabV1
- DOMAIN-SUFFIX,disneyaulani.com,AkrabV1
- DOMAIN-SUFFIX,disneybaby.com,AkrabV1
- DOMAIN-SUFFIX,disneycareers.com,AkrabV1
- DOMAIN-SUFFIX,disneychannelonstage.com,AkrabV1
- DOMAIN-SUFFIX,disneychannelroadtrip.com,AkrabV1
- DOMAIN-SUFFIX,disneycruisebrasil.com,AkrabV1
- DOMAIN-SUFFIX,disneyenconcert.com,AkrabV1
- DOMAIN-SUFFIX,disneyiejobs.com,AkrabV1
- DOMAIN-SUFFIX,disneyinflight.com,AkrabV1
- DOMAIN-SUFFIX,disneyinternational.com,AkrabV1
- DOMAIN-SUFFIX,disneyinternationalhd.com,AkrabV1
- DOMAIN-SUFFIX,disneyjunior.com,AkrabV1
- DOMAIN-SUFFIX,disneyjuniortreataday.com,AkrabV1
- DOMAIN-SUFFIX,disneylandparis.com,AkrabV1
- DOMAIN-SUFFIX,disneylatino.com,AkrabV1
- DOMAIN-SUFFIX,disneymagicmoments.co.il,AkrabV1
- DOMAIN-SUFFIX,disneymagicmoments.co.uk,AkrabV1
- DOMAIN-SUFFIX,disneymagicmoments.co.za,AkrabV1
- DOMAIN-SUFFIX,disneymagicmoments.de,AkrabV1
- DOMAIN-SUFFIX,disneymagicmoments.es,AkrabV1
- DOMAIN-SUFFIX,disneymagicmoments.fr,AkrabV1
- DOMAIN-SUFFIX,disneymagicmoments.gen.tr,AkrabV1
- DOMAIN-SUFFIX,disneymagicmoments.gr,AkrabV1
- DOMAIN-SUFFIX,disneymagicmoments.it,AkrabV1
- DOMAIN-SUFFIX,disneymagicmoments.pl,AkrabV1
- DOMAIN-SUFFIX,disneymagicmomentsme.com,AkrabV1
- DOMAIN-SUFFIX,disneyme.com,AkrabV1
- DOMAIN-SUFFIX,disneymeetingsandevents.com,AkrabV1
- DOMAIN-SUFFIX,disneymovieinsiders.com,AkrabV1
- DOMAIN-SUFFIX,disneymusicpromotion.com,AkrabV1
- DOMAIN-SUFFIX,disneynewseries.com,AkrabV1
- DOMAIN-SUFFIX,disneynow.com,AkrabV1
- DOMAIN-SUFFIX,disneypeoplesurveys.com,AkrabV1
- DOMAIN-SUFFIX,disneyplus.bn5x.net,AkrabV1
- DOMAIN-SUFFIX,disneyplus.com,AkrabV1
- DOMAIN-SUFFIX,disneyplus.com.ssl.sc.omtrdc.net,AkrabV1
- DOMAIN-SUFFIX,disneyprivacycenter.com,AkrabV1
- DOMAIN-SUFFIX,disneyredirects.com,AkrabV1
- DOMAIN-SUFFIX,disneysrivieraresort.com,AkrabV1
- DOMAIN-SUFFIX,disneystore.com,AkrabV1
- DOMAIN-SUFFIX,disneystreaming.com,AkrabV1
- DOMAIN-SUFFIX,disneysubscription.com,AkrabV1
- DOMAIN-SUFFIX,disneytermsofuse.com,AkrabV1
- DOMAIN-SUFFIX,disneytickets.co.uk,AkrabV1
- DOMAIN-SUFFIX,disneyturkiye.com.tr,AkrabV1
- DOMAIN-SUFFIX,disneytvajobs.com,AkrabV1
- DOMAIN-SUFFIX,disneyworld-go.com,AkrabV1
- DOMAIN-SUFFIX,dlp-media.com,AkrabV1
- DOMAIN-SUFFIX,dmed.technology,AkrabV1
- DOMAIN-SUFFIX,dssott.com,AkrabV1
- DOMAIN-SUFFIX,dtci.co,AkrabV1
- DOMAIN-SUFFIX,dtci.technology,AkrabV1
- DOMAIN-SUFFIX,edgedatg.com,AkrabV1
- DOMAIN-SUFFIX,espn.co.uk,AkrabV1
- DOMAIN-SUFFIX,espn.com,AkrabV1
- DOMAIN-SUFFIX,espn.hb.omtrdc.net,AkrabV1
- DOMAIN-SUFFIX,espn.net,AkrabV1
- DOMAIN-SUFFIX,espncdn.com,AkrabV1
- DOMAIN-SUFFIX,espndotcom.tt.omtrdc.net,AkrabV1
- DOMAIN-SUFFIX,espnqa.com,AkrabV1
- DOMAIN-SUFFIX,execute-api.us-east-1.amazonaws.com,AkrabV1
- DOMAIN-SUFFIX,go-disneyworldgo.com,AkrabV1
- DOMAIN-SUFFIX,go.com,AkrabV1
- DOMAIN-SUFFIX,hotstar-cdn.net,AkrabV1
- DOMAIN-SUFFIX,hotstar.com,AkrabV1
- DOMAIN-SUFFIX,hotstarext.com,AkrabV1
- DOMAIN-SUFFIX,hsprepack.akamaized.net,AkrabV1
- DOMAIN-SUFFIX,js-agent.newrelic.com,AkrabV1
- DOMAIN-SUFFIX,marvel.com,AkrabV1
- DOMAIN-SUFFIX,marvel10thanniversary.com,AkrabV1
- DOMAIN-SUFFIX,marveldimensionofheroes.com,AkrabV1
- DOMAIN-SUFFIX,marvelparty.net,AkrabV1
- DOMAIN-SUFFIX,marvelpinball.com,AkrabV1
- DOMAIN-SUFFIX,marvelsdoubleagent.com,AkrabV1
- DOMAIN-SUFFIX,marvelspotlightplays.com,AkrabV1
- DOMAIN-SUFFIX,marvelsuperheroseptember.com,AkrabV1
- DOMAIN-SUFFIX,marvelsuperwar.com,AkrabV1
- DOMAIN-SUFFIX,mickey.tv,AkrabV1
- DOMAIN-SUFFIX,moviesanywhere.com,AkrabV1
- DOMAIN-SUFFIX,natgeomaps.com,AkrabV1
- DOMAIN-SUFFIX,nationalgeographic.com,AkrabV1
- DOMAIN-SUFFIX,nationalgeographicpartners.com,AkrabV1
- DOMAIN-SUFFIX,ngeo.com,AkrabV1
- DOMAIN-SUFFIX,nomadlandmovie.ch,AkrabV1
- DOMAIN-SUFFIX,playmation.com,AkrabV1
- DOMAIN-SUFFIX,shopdisney.com,AkrabV1
- DOMAIN-SUFFIX,shops-disney.com,AkrabV1
- DOMAIN-SUFFIX,sorcerersarena.com,AkrabV1
- DOMAIN-SUFFIX,spaindisney.com,AkrabV1
- DOMAIN-SUFFIX,star-brasil.com,AkrabV1
- DOMAIN-SUFFIX,star-latam.com,AkrabV1
- DOMAIN-SUFFIX,starwars.com,AkrabV1
- DOMAIN-SUFFIX,starwarsgalacticstarcruiser.com,AkrabV1
- DOMAIN-SUFFIX,starwarskids.com,AkrabV1
- DOMAIN-SUFFIX,streamingdisney.net,AkrabV1
- DOMAIN-SUFFIX,themarvelexperiencetour.com,AkrabV1
- DOMAIN-SUFFIX,thestationbymaker.com,AkrabV1
- DOMAIN-SUFFIX,thewaltdisneycompany.com,AkrabV1
- DOMAIN-SUFFIX,thisispolaris.com,AkrabV1
- DOMAIN-SUFFIX,watchdisneyfe.com,AkrabV1
- DOMAIN-SUFFIX,watchespn.com,AkrabV1
- PROCESS-NAME,com.disney.datg.videoplatforms.android.abc,AkrabV1
- PROCESS-NAME,com.disney.disneyplus,AkrabV1
- MATCH,GLOBAL
