---
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
allow-lan: true
mode: rule
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: "/usr/share/openclash/ui"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.24.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.netflix.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    fake-ip-filter:
    - "+.pool.ntp.org"
    - ntp7.*.com
    - ntp6.*.com
    - ntp5.*.com
    - ntp4.*.com
    - ntp3.*.com
    - ntp2.*.com
    - ntp1.*.com
    - ntp.*.com
    - time7.*.com
    - time6.*.com
    - time5.*.com
    - time4.*.com
    - time3.*.com
    - time2.*.com
    - time1.*.com
    - time.*.apple.com
    - time.*.edu.cn
    - time.*.gov
    - time.*.com
    - "*.home.arpa"
    - "*.local"
    - "*.test"
    - "*.localhost"
    - "*.invalid"
    - "*.example"
    - "*.localdomain"
    - time1.cloud.tencent.com
    - "*.ntp.org"
    - "*.time.edu"
    - "*.lan"
    - "*.ntp.org.cn"
    - "*.time.edu.cn"
    - "+.*"
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  - https://dns.google/dns-query
  - tls://dns.google
  - dhcp://"eth1"
  - dhcp://"wwan0"
  - dhcp://"eth2"
  - 192.168.8.1
  - 10.112.94.22
  - 192.168.9.1
  default-nameserver:
  - 8.8.8.8
  - 1.1.1.1
  - 8.8.4.4
  - 1.0.0.1
  - 192.168.8.1
  - 10.112.94.22
  - 192.168.9.1
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time-ios.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - "+.google.com"
  - Mijia Cloud
  - "+.cmbchina.com"
  - "+.cmbimg.com"
  - "+.*"
  fake-ip-range: 198.18.0.1/16
proxy-providers:
  Paket-Eth1:
    type: http
    path: "./proxy_provider/akun-eth1.yaml"
    url:
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
  Paket-Wwan0:
    type: http
    path: "./proxy_provider/akun-wwan0.yaml"
    url:
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
proxy-groups:
- name: IDTECH-META
  type: select
  disable-udp: false
  proxies:
  - S
  - P
  - FB
  - LB
- name: S
  type: select
  disable-udp: false
  proxies:
  - ETH1-UMUM
  - WWAN0-UMUM
- name: P
  type: url-test
  disable-udp: false
  proxies:
  - ETH1-UMUM
  - WWAN0-UMUM
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: FB
  type: select
  disable-udp: false
  proxies:
  - ETH1-UMUM
  - WWAN0-UMUM
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: LB
  type: load-balance
  strategy: round-robin
  disable-udp: false
  proxies:
  - ETH1-UMUM
  - WWAN0-UMUM
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: WWAN0-UMUM
  type: select
  disable-udp: false
  use:
  - Paket-Wwan0
  interface-name: wwan0
- name: ETH1-UMUM
  type: select
  disable-udp: false
  use:
  - Paket-Eth1
  interface-name: eth1
- name: ETH2-GAME
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  interface-name: eth2
rule-providers:
  Rule-Umum:
    type: file
    behavior: classical
    path: "./rule_provider/khusus-umum.yaml"
    url:
    interval: 3600
  Rule-Game:
    type: http
    behavior: classical
    path: "./rule_provider/khusus-game.yaml"
    url:
    interval: 3600
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,Rule-Umum,IDTECH-META
- RULE-SET,Rule-Game,ETH2-GAME
- GEOIP,ID,IDTECH-META
- MATCH,IDTECH-META
tun:
  enable: true
  stack: system
  device: utun
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
profile:
  store-selected: true
  store-fake-ip: true
secret: idtech
bind-address: "*"
experimental:
  sniff-tls-sni: true
sniffer:
  enable: true
  parse-pure-ip: true
